steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - --branch=$BRANCH_NAME
      - --depth=1
      - https://github.com/StratusNetwork/ProtocolSupport.git
      - build
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - README.md
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/master/github-stratusnetwork-protocolsupport
    wait_for: ['-']
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/master/.m2
      - .
    wait_for: ['-']
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - --volume=/workspace/build:/root/build
      - --volume=/workspace/.m2:/root/.m2/repository
      - gcr.io/$PROJECT_ID/gradle
      - bash
      - -c
      - cd /root/build && gradle build && mv target/ProtocolSupport.jar /root/.m2/repository/other/protocolsupport.jar
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -rn
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/master
